import { expect, test } from "@playwright/test";
import { toStorefrontProduct } from "@/lib/storefront-products";

test("projects a full product into the safe storefront shape", () => {
    const fullProduct = {
        id: "miko-animals",
        slug: "miko-meets-the-animals",
        title: "Miko Meets the Animals",
        shortDescription: "First animal words.",
        longDescription: "A long product description that must stay on the server.",
        price: 24900,
        currency: "INR",
        ageRange: "0-5 years",
        coverPath: "covers/miko-animals.webp",
        images: [
            { path: "inside/second.webp", role: "inside", alt: "Second spread", order: 2 },
            { path: "covers/miko-animals.webp", role: "cover", alt: "Cover", order: 0 },
            { path: "inside/first.webp", role: "inside", order: 1 },
            { path: "inside/third.webp", role: "inside", alt: 99, order: "last" },
            { path: 42, role: "inside", alt: "Invalid path", order: 3 },
        ],
        inventoryQuantity: 50,
        inventoryStatus: "IN_STOCK",
        sku: "MIKO-ANIMALS",
        weightGrams: 250,
        dimensionsCm: { width: 20, height: 20, depth: 1 },
        pages: 24,
        format: "Board Book",
        author: "NitiVidya Books",
        illustrator: "NitiVidya Studio",
        publisher: "NitiVidya Books",
        language: "Hindi + English",
        isbn: "9780000000000",
        metaTitle: "Miko Meets the Animals",
        metaDescription: "SEO description",
        ogImagePath: "og/miko-animals.webp",
        twitterCard: "summary_large_image",
        hasHeroSlide: true,
        heroPriority: 1,
        tags: ["animals", "bilingual"],
        collections: ["miko-series"],
        isFeatured: true,
        published: true,
        publishedAt: new Date("2026-01-01T00:00:00.000Z"),
        createdAt: new Date("2025-01-01T00:00:00.000Z"),
        updatedAt: new Date("2026-01-02T00:00:00.000Z"),
        status: "ACTIVE",
        meta: { campaign: "launch" },
        amazonUrl: "https://amazon.in/example",
    };

    expect(toStorefrontProduct(fullProduct)).toEqual({
        id: "miko-animals",
        slug: "miko-meets-the-animals",
        title: "Miko Meets the Animals",
        price: 24900,
        ageRange: "0-5 years",
        coverPath: "covers/miko-animals.webp",
        pages: 24,
        format: "Board Book",
        language: "Hindi + English",
        tags: ["animals", "bilingual"],
        collections: ["miko-series"],
        heroPriority: 1,
        insideImages: [
            { path: "inside/second.webp", alt: "Second spread", order: 2 },
            { path: "inside/first.webp", alt: "", order: 1 },
            { path: "inside/third.webp", alt: "", order: 0 },
        ],
    });
});
